#include "d3xx.h"
 
class d304 : public d3xx
{
  public: 
    std::string GetGroupName()
    {
	return "181 to 240";
    }
    d304() 
    { 
      std::string * e140 = new std::string[20] { "刀", "トウ", "x", "かたな", "x", "sabre", "x", "x", "sword", "x", "x", "刀（かたな）", "日本刀（にほんとう）", "剃刀（かみそり）", "sabre de samouraï", "sabre japonais", "rasoir", "samourai sword", "Japanese sword", "razor" };
    ksdb[0] = e140;
    std::string * e141 = new std::string[20] { "冬", "トウ", "x", "ふゆ", "x", "hiver", "x", "x", "winter", "x", "x", "冬休み（ふゆやすみ）", "冬眠（とうみん）", "x", "vacances d'hiver", "hibernation", "x", "winter holidays", "hibernation", "x" };
    ksdb[1] = e141;
    std::string * e142 = new std::string[20] { "当", "トウ", "x", "あ（たる）", "x", "atteindre", "appliquer à", "approprié", "to hit", "to apply", "appropriate", "当時（とうじ）", "当然（とうぜん）", "当てる（あてる）", "en ce temps-là", "comme de bien entendu", "atteindre (transitif)", "in those days, at that time", "as a matter of course", "to hit, to apply (v.t.)" };
    ksdb[2] = e142;
    std::string * e143 = new std::string[20] { "東", "トウ", "x", "ひがし", "x", "Est, Orient", "x", "x", "east", "x", "x", "東洋（とうよう）", "東京（とうきょう）", "東南アジア（とうなんあじあ）", "Orient", "Tōkyō", "Asie du Sud-Est", "Orient", "Tōkyō", "South-East Asia" };
    ksdb[3] = e143;
    std::string * e144 = new std::string[20] { "答", "トウ", "x", "こた（える）", "x", "répondre", "x", "x", "answer", "x", "x", "解答（かいとう）", "答え（こたえ）", "x", "réponse, solution", "réponse", "x", "answer, solution", "answer", "x" };
    ksdb[4] = e144;
    std::string * e145 = new std::string[20] { "頭", "トウ", "ズ", "あたま", "かしら", "tête", "(partie", "supérieure)", "head", "top", "start", "頭が痛い（あたまがいたい）", "二頭の牛（にとうのうし）", "x", "avoir mal à la tête", "2 vaches (= 2 têtes )", "x", "to have a headache", "2 cows (counter for large animals)", "x" };
    ksdb[5] = e145;
    std::string * e146 = new std::string[20] { "同", "ドウ", "x", "おなじ", "x", "même", "similaire", "x", "same", "x", "x", "同時に（どうじに）", "同意（どうい）", "共同（きょうどう）", "en même temps", "accord, consentement", "coopération, collaboration", "at the same time", "agreement, consent", "cooperation, collaboration" };
    ksdb[6] = e146;
    std::string * e147 = new std::string[20] { "道", "ドウ", "トウ", "みち", "x", "chemin", "voie", "art", "way", "road", "x", "鉄道（てつどう）", "回り道（まわりみち）", "茶道（さどう）（ちゃどう）", "chemin de fer", "détour", "cérémonie du thé", "railway, railroad", "detour", "tea ceremony" };
    ksdb[7] = e147;
    std::string * e148 = new std::string[20] { "読", "ドク", "トク", "よ（む）", "x", "lire", "x", "x", "to read", "x", "x", "読者（どくしゃ）", "読売（よみうり）", "読み方（よみかた）", "lecteur", "Yomiuri (nom d'un journal)", "prononciation(s) d'un kanji", "reader", "Yomiuri (newspaper)", "reading(s) of a kanji" };
    ksdb[8] = e148;
    std::string * e149 = new std::string[20] { "南", "ナン", "x", "みなみ", "x", "Sud", "x", "x", "south", "x", "x", "東南アジア（とうなんあじあ）", "南太平洋（みなみたいへいよう）", "x", "Asie du Sud-Est", "Pacifique sud", "x", "South-East Asia", "South Pacific", "x" };
    ksdb[9] = e149;
    std::string * e1410 = new std::string[20] { "馬", "バ", "x", "うま", "ま", "cheval", "x", "x", "horse", "x", "x", "競馬（けいば）", "群馬県（ぐんまけん）", "x", "courses de chevaux", "Préfecture de Gunma", "x", "horse-racing", "Gunma Prefecture", "x" };
    ksdb[10] = e1410;
    std::string * e1411 = new std::string[20] { "売", "バイ", "x", "う（る）", "う（れる）", "vendre", "se vendre", "x", "to sell", "x", "x", "売買（ばいばい）", "売り切れ（うりきれ）", "売り上げ（うりあげ）", "commerce", "en rupture de stock", "chiffre d'affaires", "trade, commerce", "sold-out", "sales amount" };
    ksdb[11] = e1411;
    std::string * e1412 = new std::string[20] { "買", "バイ", "x", "か（う）", "x", "acheter", "x", "x", "to buy", "x", "x", "買い手（かいて）", "買い物（かいもの）", "x", "l'acheteur", "(faire) les courses", "x", "buyer", "(to go) shopping", "x" };
    ksdb[12] = e1412;
    std::string * e1413 = new std::string[20] { "麦", "バク", "x", "むぎ", "x", "céréale", "x", "x", "barley", "wheat", "x", "小麦（こむぎ）", "麦茶（むぎちゃ）", "からす麦（からすむぎ）", "blé", "mugicha (thé à l'orge)", "avoine", "corn (UK), wheat (USA)", "mugicha (barley tea)", "oats" };
    ksdb[13] = e1413;
    std::string * e1414 = new std::string[20] { "半", "ハン", "x", "なか（ば）", "x", "moitié", "milieu", "x", "half", "middle", "x", "半分（はんぶん）", "半島（はんとう）", "半径（はんけい）", "la moitié", "péninsule", "rayon (d'un cercle)", "half", "peninsular", "radius" };
    ksdb[14] = e1414;
    std::string * e1415 = new std::string[20] { "番", "バン", "x", "x", "x", "(A qui le) tour", "numéro", "garde", "turn", "number", "guard", "一番（いちばん）", "番号（ばんごう）", "番組（ばんぐみ）", "le meilleur, numéro un", "numéro (de compte par ex.)", "émission (par ex. télé)", "best, number one", "(account) number", "program(me) (e.g. T.V.)" };
    ksdb[15] = e1415;
    std::string * e1416 = new std::string[20] { "父", "フ", "x", "ちち", "x", "père", "x", "x", "father", "x", "x", "お父さん（おとうさん）", "お祖父さん（おじいさん）", "神父（しんぷ）", "Père (poli)", "Grand-père (poli)", "prêtre catholique", "Father (polite)", "Grand-father (polite)", "Catholic priest" };
    ksdb[16] = e1416;
    std::string * e1417 = new std::string[20] { "風", "フウ", "x", "かぜ", "x", "vent", "style", "à la ...", "wind", "style", "x", "台風（たいふう）", "北風（きたかぜ）", "和風（わふう）", "typhon", "vent du nord", "de style japonais traditionnel", "typhoon", "North wind", "Japanese style" };
    ksdb[17] = e1417;
    std::string * e1418 = new std::string[20] { "分", "ブン", "ブ", "わ（かる）", "わ（ける）", "diviser", "minute", "comprendre", "to divide", "minute", "to understand", "一分（いっぷん）", "分かりにくい（わかりにくい）", "分ける（わける）", "une minute", "difficile à comprendre", "diviser, séparer", "one minute", "hard to understand", "divide, separate" };
    ksdb[18] = e1418;
    std::string * e1419 = new std::string[20] { "聞", "ブン", "モン", "き（く）", "き（こえる）", "entendre", "écouter", "demander", "to hear", "to ask", "to listen", "新聞（しんぶん）", "聞き取り（ききとり）", "x", "journal", "compréhension orale", "x", "newspaper", "listening comprehension", "x" };
    ksdb[19] = e1419;
    std::string * e1420 = new std::string[20] { "米", "ベイ", "マイ", "こめ", "x", "riz", "Amérique", "x", "rice", "America", "x", "玄米（げんまい）", "日米（にちべい）", "米ドル（べいどる）", "riz complet", "américano-japonais", "dollar américain", "unpolished rice, brown rice", "Japan-America", "American dollar" };
    ksdb[20] = e1420;
    std::string * e1421 = new std::string[20] { "歩", "ホ", "x", "ある（く）", "あゆ（む）", "marcher", "x", "x", "to walk", "x", "x", "歩行者（ほこうしゃ）", "進歩（しんぽ）", "一歩一歩（いっぽいっぽ）", "piéton", "progrès", "pas à pas, progressivement", "pedestrian", "progress", "step by step" };
    ksdb[21] = e1421;
    std::string * e1422 = new std::string[20] { "母", "ボ", "x", "はは", "x", "mère", "x", "x", "mother", "x", "x", "お母さん（おかあさん）", "お祖母さん（おばあさん）", "母音（ぼいん）", "Mère, maman (poli)", "Grand-mère (poli)", "voyelle", "mother (polite)", "grandmother (polite)", "vowel" };
    ksdb[22] = e1422;
    std::string * e1423 = new std::string[20] { "方", "ホウ", "x", "かた", "x", "direction", "personne", "manière", "direction", "person", "way (method)", "方面（ほうめん）", "日本の方（にほんのかた）", "読み方（よみかた）", "direction (orientation)", "un Japonais, une Japonaise (poli)", "lecture (d'un kanji par ex.)", "direction, field (e.g. of study)", "a Japanese (polite)", "reading (e.g. of a kanji)" };
    ksdb[23] = e1423;
    std::string * e1424 = new std::string[20] { "北", "ホク", "ボク", "きた", "x", "nord", "x", "x", "North", "x", "x", "北海道（ほっかいどう）", "北風（きたかぜ）", "東北（とうほく）", "Hokkaidō", "vent du nord, vent froid", " Tōhoku (nord-est de Honshū)", "Hokkaidō", "north wind", " Tōhoku (north-east of Honshū)" };
    ksdb[24] = e1424;
    std::string * e1425 = new std::string[20] { "毎", "マイ", "x", "ごと", "x", "chaque", "chacun", "x", "each", "every", "x", "毎日（まいにち）", "毎週（まいしゅう）", "毎年（まいねん）（まいとし）", "chaque jour", "chaque semaine", "chaque année", "every day", "every week", "every year" };
    ksdb[25] = e1425;
    std::string * e1426 = new std::string[20] { "妹", "マイ", "x", "いもうと", "x", "jeune soeur", "soeur cadette", "x", "young sister", "x", "x", "姉妹（しまい）", "妹（いもうと）", "x", "(des) soeurs", "jeune soeur", "x", "sisters", "young sister", "x" };
    ksdb[26] = e1426;
    std::string * e1427 = new std::string[20] { "明", "メイ", "ミョウ", "あか（るい）", "あ（ける）", "lumineux", "clair", "gai", "bright", "clear", "cheerful", "明日（あした、あす）", "明治時代（めいじじだい）", "明け方（あけがた）", "demain", "L'Ère Meiji", "l'aurore, l'aube", "tomorrow", "Meiji Era", "dawn" };
    ksdb[27] = e1427;
    std::string * e1428 = new std::string[20] { "鳴", "メイ", "x", "な（く）", "な（る）", "cri (d'animal)", "crier", "x", "to cry (animal)", "x", "x", "鳴く（なく）", "鳴り響く（なりひびく）", "x", "aboyer, coasser, etc. (selon l'animal)", "faire écho, résonner", "x", "to bark, to croak, etc...", "to echo, to resound, to reverberate", "x" };
    ksdb[28] = e1428;
    std::string * e1429 = new std::string[20] { "毛", "モウ", "x", "け", "x", "poil", "cheveu", "x", "hair", "x", "x", "髪の毛（かみのけ）", "毛虫（けむし）", "毛布（もうふ）", "cheveux", "chenille", "couverture en laine", "hair (head)", "caterpillar", "wool blanket" };
    ksdb[29] = e1429;
    std::string * e1430 = new std::string[20] { "門", "モン", "x", "かど", "x", "porte", "portail", "x", "gate", "door", "x", "門番（もんばん）", "門松（かどまつ）", "凱旋門（がいせんもん）", "portier", "décoration du Nouvel An (portes)", "Arc de Triomphe (Paris), arc de triomphe", "doorman", "New Year decoration (at the door) ", "Arch of Triumph " };
    ksdb[30] = e1430;
    std::string * e1431 = new std::string[20] { "夜", "ヤ", "x", "よ", "よる", "nuit", "x", "x", "night", "x", "x", "夜明け（よあけ）", "今夜（こんや）", "夜間（やかん）", "aube, aurore", "ce soir, cette nuit", "la nuit ", "dawn, daybreak", "this evening, tonight", "nighttime, at night" };
    ksdb[31] = e1431;
    std::string * e1432 = new std::string[20] { "野", "ヤ", "x", "の", "x", "champ", "x", "x", "field", "x", "x", "野菜（やさい）", "野生（やせい）", "野党（やとう）", "légume", "sauvage (animal)", "l'opposition (en politique)", "vegetable", "wild (animal)", "opposition party" };
    ksdb[32] = e1432;
    std::string * e1433 = new std::string[20] { "友", "ユウ", "x", "とも", "x", "ami", "x", "x", "friend", "x", "x", "友だち（ともだち）", "友情（ゆうじょう）", "x", "ami(s), amie(s)", "amitié", "x", "friend(s)", "friendship", "x" };
    ksdb[33] = e1433;
    std::string * e1434 = new std::string[20] { "用", "ヨウ", "x", "もち（いる）", "x", "usage", "utilisation", "x", "use", "task", "business", "用心する（ようじんする）", "用事（ようじ）", "用品（ようひん）", "faire attention, prendre garde", "(avoir des) choses à faire", "articles, produits", "to be on one's guard, to be careful", "things to do, to attend to", "articles, supplies, parts" };
    ksdb[34] = e1434;
    std::string * e1435 = new std::string[20] { "曜", "ヨウ", "x", "x", "x", "jour de", "la semaine", "x", "day of the week", "x", "x", "日曜日（にちようび）", "何曜日（なんようび）", "x", "dimanche", "Quel jour ?", "x", "Sunday", "What day?", "x" };
    ksdb[35] = e1435;
    std::string * e1436 = new std::string[20] { "来", "ライ", "x", "く（る）", "x", "venir", "x", "x", "to come", "x", "x", "来年（らいねん）", "出来る（できる）", "来る（くる）", "l'année prochaine", "être possible", "venir, arriver", "next year", "to be possible", "to come, to arrive" };
    ksdb[36] = e1436;
    std::string * e1437 = new std::string[20] { "楽", "ラク", "ガク", "たの（しい）", "たの（しむ）", "plaisir", "musique", "x", "pleasure", "music", "x", "楽器（がっき）", "楽しむ（たのしむ）", "楽園（らくえん）", "instrument de musique", "prendre plaisir à", "parc d'amusement, paradis", "musical instrument", "to enjoy oneself", "amusement park, paradise" };
    ksdb[37] = e1437;
    std::string * e1438 = new std::string[20] { "里", "リ", "x", "さと", "x", "village", "lieue (mesure)", "x", "village ", "league (measure)", "x", "ふる里（ふるさと）", "万里の長城（ばんりのちょうじょう）", "x", "ville natale", "                Grande Muraille de Chine", "x", "hometown", "                Great Wall of China", "x" };
    ksdb[38] = e1438;
    std::string * e1439 = new std::string[20] { "理", "リ", "x", "x", "x", "raison", "x", "x", "reason", "rational", "x", "理想（りそう）", "理由（りゆう）", "無理（むり）", "idéal", "raison, prétexte, motif", "impossible", "ideal", "reason, pretext, motive", "impossible" };
    ksdb[39] = e1439;
    std::string * e1440 = new std::string[20] { "話", "ワ", "x", "はなし", "はな（す）", "parole", "parler", "x", "speech", "to talk", "x", "電話（でんわ）", "会話（かいわ）", "話題（わだい）", "téléphone", "conversation", "sujet de discussion", "telephone", "conversation", "topic, subject" };
    ksdb[40] = e1440;
    std::string * e1441 = new std::string[20] { "悪", "アク", "オ", "わる（い）", "x", "mal", "méchanceté", "x", "evil", "wickedness", "x", "悪臭（あくしゅう）", "悪口（わるぐち）", "最悪（さいあく）", "puanteur, miasme", "insulte, calomnie", "(le) pire", "stink, stench, bad odor", "abuse, insult, slander", "the worst" };
    ksdb[41] = e1441;
    std::string * e1442 = new std::string[20] { "安", "アン", "x", "やす（い）", "やす（まる）", "calme", "serein", "bon marché", "quiet", "peace", "cheap", "安い（やすい）", "安全（あんぜん）", "不安定（ふあんてい）", "bon marché", "sécurité", "instabilité, insécurité", "cheap, inexpensive", "safety, security", "instability, insecurity" };
    ksdb[42] = e1442;
    std::string * e1443 = new std::string[20] { "暗", "アン", "x", "くら（い）", "x", "sombre", "morose", "x", "dark", "gloomy", "x", "暗号（あんごう）", "暗記（あんき）", "真っ暗（まっくら）", "code secret , mot de passe", "mémorisation", "tout noir", "secret code, password", "memorization, learning by heart", "pitch dark" };
    ksdb[43] = e1443;
    std::string * e1444 = new std::string[20] { "医", "イ", "x", "x", "x", "médecine", "docteur", "traitement", "medicine", "doctor", "cure", "医者（いしゃ）", "医療（いりょう）", "医学（いがく）", "docteur ", "traitement médical", "la médecine", "doctor", "medical treatment", "medical science, medicine" };
    ksdb[44] = e1444;
    std::string * e1445 = new std::string[20] { "意", "イ", "x", "x", "x", "pensée", "volonté", "x", "mind", "thought", "will", "意見（いけん）", "注意（ちゅうい）", "意志（いし）", "opinion", "(faire) attention", "volonté", "opinion", "(pay) attention", "will, volition" };
    ksdb[45] = e1445;
    std::string * e1446 = new std::string[20] { "育", "イク", "x", "そだ（つ）", "そだ（てる）", "éduquer", "élever", "x", "to raise", "to educate", "x", "教育（きょういく）", "育てる（そだてる）", "x", "éducation", "élever", "x", "education", "to raise, to bring up", "x" };
    ksdb[46] = e1446;
    std::string * e1447 = new std::string[20] { "員", "イン", "x", "x", "x", "membre", "x", "x", "member", "x", "x", "会社員（かいしゃいん）", "委員（いいん）", "全員（ぜんいん）", "employé d'une compagnie", "membre d'un comité", "tous les membres", "company employee", "committee member", "all members" };
    ksdb[47] = e1447;
    std::string * e1448 = new std::string[20] { "院", "イン", "x", "x", "x", "institut", "x", "x", "institute", "x", "x", "病院（びょういん）", "学院（がくいん）", "美容院（びよういん）", "hôpital", "institut", "salon de beauté", "hospital", "institute", "beauty parlor" };
    ksdb[48] = e1448;
    std::string * e1449 = new std::string[20] { "飲", "イン", "x", "の（む）", "x", "boire", "avaler", "x", "drink", "swallow", "x", "飲み物は？（のみものは）", "飲み屋（のみや）", "飲料（いんりょう）", "Quelle boisson prendrez-vous ?", "nomiya (taverne japonaise)", "boisson (vocabulaire commercial)", "What about a drink?", "nomiya (Japanese tavern)", "a drink" };
    ksdb[49] = e1449;
    std::string * e1450 = new std::string[20] { "運", "ウン", "x", "はこ（ぶ）", "x", "transport", "chance", "x", "transportation", "luck", "x", "運動（うんどう）", "運輸（うんゆ）", "運命（うんめい）", "mouvement", "transport", "destin", "motion, movement", "transportation", "fate" };
    ksdb[50] = e1450;
    std::string * e1451 = new std::string[20] { "泳", "エイ", "x", "およ（ぐ）", "x", "nager", "x", "x", "swim", "x", "x", "水泳（すいえい）", "泳ぐ（およぐ）", "x", "la nage", "nager", "x", "swimming", "to swim", "x" };
    ksdb[51] = e1451;
    std::string * e1452 = new std::string[20] { "駅", "エキ", "x", "x", "x", "gare", "station", "de métro", "station", "x", "x", "東京駅（とうきょうえき）", "駅前（えきまえ）", "各駅停車（かくえきていしゃ）", "gare de Tōkyō", "devant la gare", "train omnibus", "Tōkyō Station", "in front of the station", "local train (stops at every station)" };
    ksdb[52] = e1452;
    std::string * e1453 = new std::string[20] { "園", "エン", "x", "その", "x", "jardin", "parc", "x", "garden", "park", "x", "公園（こうえん）", "動物園（どうぶつえん）", "幼稚園（ようちえん）", "jardin public", "zoo, parc zoologique", "école maternelle", "public park", "zoo, zoological park", "kindergarten" };
    ksdb[53] = e1453;
    std::string * e1454 = new std::string[20] { "横", "オウ", "x", "よこ", "x", "côté", "largeur", "x", "side", "width", "x", "横幅（よこはば）", "横断歩道（おうだんほどう）", "横丁（よこちょう）", "largeur", "passage pour piétons", "ruelle, venelle", "width, breadth", "pedestrian crossing", "lane, alley, side street" };
    ksdb[54] = e1454;
    std::string * e1455 = new std::string[20] { "屋", "オク", "x", "や", "x", "magasin", "bâtiment", "x", "store", "building", "x", "屋根（やね）", "部屋（へや）", "本屋（ほんや）", "toit", "pièce", "librairie", "roof", "room", "bookstore" };
    ksdb[55] = e1455;
    std::string * e1456 = new std::string[20] { "温", "オン", "x", "あたた（かい）", "あたた（める）", "chaud", "chauffer", "x", "warm", "to warm", "x", "気温（きおん）", "温度計（おんどけい）", "温める（あたためる）", "température (de l'air)", "thermomètre", "chauffer", "temperature (of the air)", "thermometer", "to warm, to heat" };
    ksdb[56] = e1456;
    std::string * e1457 = new std::string[20] { "化", "カ", "ケ", "ば（ける）", "x", "changer", "modifier", "ensorceler", "change", "bewitch", "x", "化粧品（けしょうひん）", "強化（きょうか）", "化学（かがく）", "cosmétique", "renforcement, intensification", "chimie", "cosmetics, make-up", "strengthening, reinforcement", "chemistry" };
    ksdb[57] = e1457;
    std::string * e1458 = new std::string[20] { "荷", "カ", "x", "に", "x", "charger", "charge", "cargaison", "load", "burden", "cargo", "荷物（にもつ）", "荷船（にぶね）", "x", "bagages", "navire cargo", "x", "luggage, baggage", "freighter, cargo ship", "x" };
    ksdb[58] = e1458;
    std::string * e1459 = new std::string[20] { "界", "カイ", "x", "x", "x", "monde (fig.)", "cercle (fig.)", "frontière", "area", "boundary", "x", "世界（せかい）", "境界（きょうかい）", "官界（かんかい）", "monde, la société", "limite, frontière", "bureaucratie", "world, society", "boundary", "bureaucracy" };
    ksdb[59] = e1459;
  }
};